### ISSUE TITLE
Tracking issue for MVP demo #2

### ISSUE THREAD

**Issue by soareschen** [informalsystems/ibc-starknet#123]
## Context
This issue tracks the status of the progress toward MVP demo implementation by the end of February 2025.

## Task List
Refer to the sub-issues section for the list of items should be implemented:

### Relayer
Full IBC relaying integration on public testnets with a working CLI that users can experiment with.

- [x] #105
- [x] #133
- [x] #136
- [x] #139
- [x] #140
- [x] #149
- [x] #152
- [x] #154
- [x] #161
- [x] #165

### CLI
- [x] #109
- [x] https://github.com/informalsystems/ibc-starknet/pull/148
- [x] https://github.com/informalsystems/ibc-starknet/pull/151
- [x] https://github.com/informalsystems/ibc-starknet/pull/158
- [x] https://github.com/informalsystems/ibc-starknet/pull/159
- [x] https://github.com/informalsystems/ibc-starknet/pull/160

### e2e Tests
- [x] #121
- [x] #129
- [x] #130
- [x] #162

### Cairo Contracts
Full implementation of Cairo IBC core with mocked IBC clients for both Cosmos and Starknet.
NOTES: the mocked light clients can at best support signature-based attestation by the relayer. There is no light client security available at this point.

#### Connection Handshake
  - [x] #110
  - [x] #112
  - [x] #114
  - [x] #115
  - [x] #116

#### Channel Handshake
- [x] #108
- [x] #117

#### Packet Handlers
- [x] #93
- [x] #97
- [x] #98
- [x] #103
- [x] #104

**Comment by rnbguy** [comment]
We had a successful demo #2.
