### ISSUE TITLE
Configure CI automation for running relayer tests

### ISSUE THREAD

**Issue by soareschen** [informalsystems/ibc-starknet#31]
## Summary

The initial relayer will be tested using `starknet-devnet-rs`. We will need to configure the GitHub Actions CI to be able to run the devnet before running the relayer tests.

## Tasks

- [ ] Fetch the `starknet-devnet` executable on the CI using Nix, Docker, or downloading tarball.
- [ ] Run `starknet-devnet` with a fix seed, i.e. `--seed 0`, so that all contract addresses and signers remain the same over multiple test runs.
- [ ] Cargo run `hermes-starknet-integration-tests` while the devnet is running.
